/// <reference types="cypress" />
beforeEach(() =>{
})
it('Dslms', function(){
    cy.visit ('http://havard.deltalms.prunedge.org/')
    cy.get(':nth-child(1) > .MuiInputBase-root > .MuiInputBase-input').type('havardhs@mailinator.com')
    cy.get(':nth-child(2) > .MuiInputBase-root > .MuiInputBase-input').type('P@ssw0rd12345')
    cy.get('.MuiButton-label').click()
    cy.contains('Courses').click()
    cy.get('.jss123 > .MuiButtonBase-root > .MuiButton-label').click()
    cy.get('.MuiGrid-grid-lg-4 > .MuiBox-root > .MuiButtonBase-root > .MuiButton-label').click()
    cy.get('.MuiGrid-container > :nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('Sociology')
    cy.get(':nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('SOCIO-109')
    cy.get(':nth-child(3) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('3')
    cy.get('#mui-component-select-faculty').click()
    cy.get('[data-value="206c5a83-2378-4359-94a7-2bada8dfda10"]').click()
    cy.get('#mui-component-select-department').click()
    cy.get('[data-value="69de7b6a-0cc6-4149-af62-46922246db5a"]').click()
    cy.get('#mui-component-select-level').click()
    cy.get('[data-value="3e506964-aec1-4057-97d0-72b8690ba77c"]').click()
    cy.get('#lecturers-autocomplete').click()
    cy.get('#lecturers-autocomplete-option-1').click()
    cy.get('.MuiButton-contained > .MuiButton-label').click()
})